### ISSUE TITLE
No response in the bot after showing the first message

### ISSUE THREAD

**Issue by 411A** [Glyphack/spotify_download_bot#11]
repo deployed on heroku & the bot sent the first message successfully, but there's a problem preventing the bot to process the request...
```
2021-07-25T15:15:57.665551+00:00 heroku[web.1]: State changed from crashed to starting
2021-07-25T15:16:08.027590+00:00 heroku[web.1]: Starting process with command `python3 bot.py`
2021-07-25T15:16:29.200729+00:00 app[web.1]: An uncaught error was raised while handling the error.
2021-07-25T15:16:29.200802+00:00 app[web.1]: Traceback (most recent call last):
2021-07-25T15:16:29.200812+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 447, in process_update
2021-07-25T15:16:29.200812+00:00 app[web.1]:     handler.handle_update(update, self, check, context)
2021-07-25T15:16:29.200812+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/telegram/ext/handler.py", line 160, in handle_update
2021-07-25T15:16:29.200813+00:00 app[web.1]:     return self.callback(update, context)
2021-07-25T15:16:29.200817+00:00 app[web.1]:   File "/app/command_handlers/send_spotify_songs.py", line 10, in send_spotify_songs
2021-07-25T15:16:29.200822+00:00 app[web.1]:     song_link = context.args[0]
2021-07-25T15:16:29.200823+00:00 app[web.1]: IndexError: list index out of range
2021-07-25T15:16:29.200828+00:00 app[web.1]: 
2021-07-25T15:16:29.200835+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-07-25T15:16:29.200835+00:00 app[web.1]: 
2021-07-25T15:16:29.200835+00:00 app[web.1]: Traceback (most recent call last):
2021-07-25T15:16:29.200836+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 459, in process_update
2021-07-25T15:16:29.200836+00:00 app[web.1]:     self.dispatch_error(update, exc)
2021-07-25T15:16:29.200836+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/telegram/ext/dispatcher.py", line 679, in dispatch_error
2021-07-25T15:16:29.200837+00:00 app[web.1]:     callback(update, context)
2021-07-25T15:16:29.200837+00:00 app[web.1]: TypeError: error() missing 1 required positional argument: 'error'
2021-07-25T15:17:08.586896+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2021-07-25T15:17:08.641636+00:00 heroku[web.1]: Stopping process with SIGKILL
2021-07-25T15:17:08.745499+00:00 heroku[web.1]: Process exited with status 137
2021-07-25T15:17:08.818201+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by Glyphack** [comment]
It's a web server now should be fine with web dynos
