### ISSUE TITLE
bot doesn't download song

### ISSUE THREAD

**Issue by CALO77103** [Glyphack/spotify_download_bot#5]
Hi, I found this project for SMD and I tried it but when I put spotify link it say done without sending it so I watched on console log and I found this error
Fetching Song...
Searching for: Freddie Gibbs - Forever and a Day
Error: HTTP Error 404: Not Found        While Error : Freddie Gibbs - Forever 
and a Day
 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/spotdl/download/downloader.py", 
line 197, in download_song
    trackAudioStream = youtubeHandler.streams.filter(
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 308, in
streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 213, in
fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 187, in
player_config_args
    self._player_config_args = self.vid_info
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 278, in
vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 108, in
vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "/usr/local/lib/python3.8/dist-packages/pytube/request.py", line 53, in 
get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pytube/request.py", line 37, in 
_execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
 
Freddie Gibbs - Forever  Error              ━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
a…                                 
idk what that means bc I'm not an expert for programming but can u help me if u know the problem or fix the bug?

**Comment by Glyphack** [comment]
Hi can you give the link you tried to download with? seems like there was problem finding song on youtube

**Comment by CALO77103** [comment]
So I tried to download a spotify music and it give me that error
I finded that is a yt downloader so I put a youtube link but it say not found on spotify and it say done without music
I tried this songs
https://open.spotify.com/track/6KoduR10TkW5lwKqjA6haa?si=xg1sqBxaRnutVmCKwbcSqA
https://youtu.be/WfyVl4GCYv4
https://open.spotify.com/track/2cT0z1rbVSGl3lzaYIzMMy?si=342be5f8693b4fa9
I tried with playlist too but it's not work

**Comment by CALO77103** [comment]
I have another problem, after a copule of minutes it say this
2021-05-31T08:14:31.492420+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2021-05-31T08:14:31.557217+00:00 heroku[web.1]: Stopping process with SIGKILL
2021-05-31T08:14:31.658552+00:00 heroku[web.1]: Process exited with status 137
2021-05-31T08:14:31.874335+00:00 heroku[web.1]: State changed from starting to crashed
Can u fix that too?

**Comment by CALO77103** [comment]
I figured out the bug and I fixed it and do a pull request :D
